version: '3.4'

services:

  todowebapi:
    image: ${DOCKER_REGISTRY-}todowebapi
    build:
      context: .
      dockerfile: ToDoWebApi/Dockerfile
    depends_on:
      - "db"

  
 
  db:
      image: "mcr.microsoft.com/mssql/server"
      environment:
          MSSQL_SA_PASSWORD: "@A123456789@"
          ACCEPT_EULA: "Y"
      ports:
        - "1434:1433"
      volumes:
        -  "C:\\My Space\\DB\\docker-compos\\data:/var/opt/mssql/data"
        -  "C:\\My Space\\DB\\docker-compos\\log:/var/opt/mssql/log"
        -  "C:\\My Space\\DB\\docker-compos\\secrets:/var/opt/mssql/secrets"


